//
//  DOSBox.swift
//  WhiskyKit
//
//  This file is part of Whisky.
//
//  Whisky is free software: you can redistribute it and/or modify it under the terms
//  of the GNU General Public License as published by the Free Software Foundation,
//  either version 3 of the License, or (at your option) any later version.
//
//  Whisky is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
//  without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
//  See the GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License along with Whisky.
//  If not, see https://www.gnu.org/licenses/.
//

import Foundation
import os.log

public enum DOSBoxError: LocalizedError {
    case runtimeNotInstalled
    case programOutsideGamesFolder

    public var errorDescription: String? {
        switch self {
        case .runtimeNotInstalled:
            return "DOSBox Staging is not installed or has not been configured."
        case .programOutsideGamesFolder:
            return "DOS programs must live inside the bottle's DOS Games folder."
        }
    }
}

/// Runner support for DOS-era titles.
///
/// The app owns bottle-local metadata and config generation, while the actual
/// DOSBox executable remains an external dependency the user installs.
public enum DOSBox {
    private static let overrideKey = "dosboxBinaryOverride"

    /// Common macOS locations are checked explicitly because GUI apps do not
    /// reliably inherit the shell PATH where Homebrew installs its binaries.
    private static let bundledCandidates = [
        URL(fileURLWithPath: "/opt/homebrew/bin/dosbox-staging"),
        URL(fileURLWithPath: "/usr/local/bin/dosbox-staging"),
        URL(fileURLWithPath: "/opt/homebrew/bin/dosbox"),
        URL(fileURLWithPath: "/usr/local/bin/dosbox"),
        URL(fileURLWithPath: "/Applications/DOSBox Staging.app/Contents/MacOS/dosbox"),
        URL(fileURLWithPath: "/Applications/DOSBox.app/Contents/MacOS/DOSBox")
    ]

    public static func overrideExecutableURL() -> URL? {
        UserDefaults.standard.url(forKey: overrideKey)
    }

    public static func setOverrideExecutableURL(_ url: URL?) {
        if let url {
            UserDefaults.standard.set(url, forKey: overrideKey)
        } else {
            UserDefaults.standard.removeObject(forKey: overrideKey)
        }
    }

    public static func executableURL() -> URL? {
        let candidates = [overrideExecutableURL()].compactMap { $0 } + bundledCandidates
        return candidates.first(where: isUsableExecutable)
    }

    public static func isInstalled() -> Bool {
        executableURL() != nil
    }

    public static func version() async throws -> String {
        guard let executableURL = executableURL() else {
            throw DOSBoxError.runtimeNotInstalled
        }

        let process = Process()
        process.executableURL = executableURL
        process.arguments = ["--version"]

        let pipe = Pipe()
        process.standardOutput = pipe
        process.standardError = pipe

        try process.run()
        process.waitUntilExit()

        let output = String(data: pipe.fileHandleForReading.readDataToEndOfFile(), encoding: .utf8)?
            .trimmingCharacters(in: .whitespacesAndNewlines)

        guard let output, !output.isEmpty else {
            return executableURL.lastPathComponent
        }
        return output
    }

    public static func writeConfiguration(for bottle: Bottle) throws {
        let mouseCaptureMode = bottle.settings.dosboxCaptureMouse ? "onstart" : "onclick"
        let config = """
        # DOSBox Staging configuration generated by \(Bundle.appDisplayName)
        # Edit this file if you need advanced per-game tweaks beyond the UI.

        [sdl]
        fullscreen=\(boolString(bottle.settings.dosboxFullscreen))

        [mouse]
        mouse_capture=\(mouseCaptureMode)

        [render]
        glshader=\(bottle.settings.dosboxScaler.configValue)

        [cpu]
        core=\(bottle.settings.dosboxCore.rawValue)
        cpu_cycles=\(bottle.settings.dosboxCycles.cpuCyclesValue)
        cpu_cycles_protected=auto

        [autoexec]
        # Runtime mount commands are injected at launch so the games folder can move with the bottle.
        """

        try config.write(to: bottle.dosboxConfigURL, atomically: true, encoding: .utf8)
    }

    /// Creates the minimum folder structure the rest of the app expects for a
    /// DOSBox bottle so scanning, Finder actions, and launch commands all share
    /// the same stable root.
    public static func createBottleLayout(at bottleURL: URL) throws {
        let fileManager = FileManager.default
        try fileManager.createDirectory(at: bottleURL, withIntermediateDirectories: true)
        try fileManager.createDirectory(at: bottleURL.appending(path: "DOS Games"), withIntermediateDirectories: true)
    }

    public static func run(bottle: Bottle, programURL: URL? = nil, arguments: [String] = []) async throws {
        guard let executableURL = executableURL() else {
            throw DOSBoxError.runtimeNotInstalled
        }

        try writeConfiguration(for: bottle)

        let process = Process()
        process.executableURL = executableURL
        process.arguments = try launchArguments(for: bottle, programURL: programURL, arguments: arguments)
        process.currentDirectoryURL = bottle.dosGamesFolder
        process.qualityOfService = .userInitiated

        Logger.wineKit.info("Launching DOSBox with `\(process.arguments?.joined(separator: " ") ?? "")`")
        try process.run()
    }

    public static func generateRunCommand(
        bottle: Bottle,
        programURL: URL? = nil,
        arguments: String = ""
    ) -> String {
        guard let executableURL = executableURL() else {
            return "echo \"DOSBox Staging is not installed.\""
        }

        let launchArguments = (try? launchArguments(
            for: bottle,
            programURL: programURL,
            arguments: String.shellSplit(arguments)
        )) ?? []
        let command = ([executableURL.path] + launchArguments).map(\.esc).joined(separator: " ")
        return "cd \(bottle.dosGamesFolder.path.esc) && \(command)"
    }

    public static func startupProgramURL(for bottle: Bottle) -> URL? {
        guard let startupProgram = bottle.settings.dosboxStartupProgram else {
            return nil
        }
        return bottle.dosGamesFolder.appending(path: startupProgram)
    }

    public static func relativeProgramPath(for programURL: URL, in bottle: Bottle) throws -> String {
        let gamesRoot = bottle.dosGamesFolder.standardizedFileURL.path(percentEncoded: false)
        let programPath = programURL.standardizedFileURL.path(percentEncoded: false)

        let prefix = gamesRoot.hasSuffix("/") ? gamesRoot : gamesRoot + "/"
        guard programPath == gamesRoot || programPath.hasPrefix(prefix) else {
            throw DOSBoxError.programOutsideGamesFolder
        }

        let relativePath = String(programPath.dropFirst(prefix.count))
        return relativePath
    }

    private static func launchArguments(
        for bottle: Bottle,
        programURL: URL?,
        arguments: [String]
    ) throws -> [String] {
        // Mount the bottle-local games folder on each launch instead of storing
        // an absolute host path in the config file. That keeps bottles portable.
        let mountPath = bottle.dosGamesFolder.path(percentEncoded: false)
        var launchArguments = ["-conf", bottle.dosboxConfigURL.path(percentEncoded: false),
                               "-c", #"mount c "\#(mountPath)""#,
                               "-c", "c:"]

        let selectedProgram = programURL ?? startupProgramURL(for: bottle)
        if let selectedProgram {
            // DOSBox commands expect backslashes inside the emulated drive.
            let dosPath = try relativeProgramPath(for: selectedProgram, in: bottle)
                .replacingOccurrences(of: "/", with: "\\")
            let escapedArguments = arguments.map(\.esc).joined(separator: " ")
            let command = escapedArguments.isEmpty ? #""\#(dosPath)""#
            : #""\#(dosPath)" \#(escapedArguments)"#
            launchArguments += ["-c", command]
        }

        return launchArguments
    }

    private static func boolString(_ value: Bool) -> String {
        value ? "true" : "false"
    }

    private static func isUsableExecutable(_ url: URL) -> Bool {
        FileManager.default.isExecutableFile(atPath: url.path(percentEncoded: false))
    }
}
